farmup/farmup/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from registration import views
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('landing/',views.dashboard,name='landing'),
    path('registration/',include(('registration.urls','registration'))),
    path('test',views.test,name='test'),
    path('crop_selling/',include('shopping_cart.urls')),
    path('geo_search/',include('geosearch.urls')),
    path('credits/',include('credits.urls')),
    path('tracking/',include('tracking.urls')),
    path('fertilizer_shop/',include('fertilizer_shop.urls')),
    path('farmerandlandlord/',include('farmerandlandlord.urls'))
]+ static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

farmup/shopping_cart/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views

app_name = "shopping_cart"


urlpatterns = [
    path('buyingportal/', views.buyingpage, name='buyingpage'),
    path('addCropElements/', views.addCropElements, name='addCropElements'),
    path('', views.addCropElements, name="add_to_cart"),
    path('buyingportal/cart/',views.checkout,name="cart"),
    path('deleteitems/<item_name>',views.delete_from_cart,name="delete_item"),
    path('add',views.add),
    path('buyingportal/checkout/',views.checkout_sub,name='checkout'),
    path('buyingportal/tempcheck/',views.add_items,name='temp'),
    path('search',views.search,name='search'),
    path('increase_quan/<cropname>/<quan>/<oper>',views.change_quantity,name='increase'),

]

farmup/shopping_cart/views.py
from django.shortcuts import render,redirect
import boto3
from boto3.dynamodb.conditions import Key, Attr
from django.urls import reverse
from django.http import HttpResponse
from decimal import *
from registration.login_required import is_loggedin
import uuid
from django.utils.crypto import get_random_string
import datetime
import textdistance

def add(request):
    dynamodb=boto3.resource('dynamodb')
    table=dynamodb.Table('cropinfo')
    items = ['tomato','potato','carrot','watermelon']
    cost = ['40','20','45','35']
    stock = [10,30,20,30]
    links = ['https://uploads.scratch.mit.edu/users/avatars/443/3561.png','https://3.imimg.com/data3/OE/IJ/MY-331481/potato-250x250.jpg','https://www.fondation-louisbonduelle.org/wp-content/uploads/2016/10/carotte_222805396.png','https://lh3.googleusercontent.com/proxy/K6e0y7jx1yU2gtlPntCMPCVW327GNnKcsk26RDSA_PvCVqzHq8hvIECZP4Rs-O6xHIXpDngdgYlnahn8l7UiIZI4ZA05258I38m8r-RU3tIWyEYthJER1FbayHWHbEc']
    for i in range(len(items)):
        table.put_item(
            Item={
                'crop_id': str(i+1),
                'name': items[i],
                'image_link': links[i],
                'cost':cost[i],
                'stock':stock[i]
            }
        )
    return HttpResponse('add products')


def addCropElements(request):
    dynamodb=boto3.resource('dynamodb')
    table=dynamodb.Table('Order')
    id = request.POST['crop_name']
    prod_id = request.POST['id']
    quantity = request.POST['quantity']
    typeof = request.POST['type']
    order_ids = []
    for k in table.scan()['Items']:
        order_ids.append(int(k['order_id']))
    type_add = ''
    if typeof == 'crops':
        table_crop = dynamodb.Table('cropinfo')
        crops_id = table_crop.scan()['Items']
        c_id = 0
        order_cost = 0
        for i in crops_id:
            if i['name']==id:
                order_cost += int(i['cost'])
                c_id += int(i['crop_id'])
        type_add = 'crops'
    elif typeof == 'fertilizer':
        table_crop = dynamodb.Table('fertilizer_info')
        crops_id = table_crop.scan()['Items']
        c_id = 0
        order_cost = 0
        for i in crops_id:
            print(i['fertilizer_id'], prod_id)
            if i['fertilizer_id']==prod_id:
                order_cost += int(i['cost'])
                c_id += int(i['fertilizer_id'])
        print(c_id)
        type_add = 'fertilizer'
    if order_ids:
        ids = str(max(order_ids)+1)
    else:
        ids = '1'
    table.put_item(
        Item = {
            'order_id': ids,
            'crop_id':c_id,
            'username':request.session['username'],
            'email':request.session['email'],
            'quantity':quantity,
            'cost':int(quantity)*order_cost,
            'is_purchased':False,
            'delivery_status':'Not Purchased',
            'ordered_date':datetime.date.today().strftime('%B %d,%Y'),
            'ordered_time':datetime.datetime.now().time().strftime('%H:%M:%S'),
            'type':type_add

        }
    )
    # if typeof == 'crops':

    if typeof=='crops':
        table_crop = dynamodb.Table('cropinfo')
        crops_id = table_crop.scan()['Items']
        print(crops_id)
        print(type(c_id))
        crops = table_crop.scan(
            FilterExpression = Attr('crop_id').eq(str(c_id))
        )['Items']
        print(crops)
        # print(crops[0]['stock'])
        cur_stock = crops[0]['stock']
        table_crop.update_item(
            Key={
                'crop_id':str(c_id)
            },
         UpdateExpression = "set stock = :r",
        ExpressionAttributeValues={
            ':r': int(cur_stock) - int(quantity),
            },
            ReturnValues="UPDATED_NEW"

        )
    if typeof=='fertilizer':
        table_crop = dynamodb.Table('fertilizer_info')
        crops_id = table_crop.scan()['Items']
        crops = table_crop.scan(
            FilterExpression = Attr('fertilizer_id').eq(str(c_id))
        )['Items']
        print(crops[0]['quantity'])
        cur_stock = crops[0]['quantity']
        table_crop.update_item(
            Key={
                'fertilizer_id':str(c_id)
            },
         UpdateExpression = "set quantity = :r",
        ExpressionAttributeValues={
            ':r': int(cur_stock) - int(quantity),
            },
            ReturnValues="UPDATED_NEW"

        )

    return redirect(reverse('shopping_cart:buyingpage'))



def checkout(request):
    dynamodb = boto3.resource('dynamodb')
    table_order = dynamodb.Table('Order')
    table_crop = dynamodb.Table('cropinfo')
    table_fert = dynamodb.Table('fertilizer_info')
    crops = table_crop.scan()
    ferts = table_fert.scan()
    crops_ordered_images = []
    crops_ordered_names = []
    crops_ordered_cost = []
    crops_ava = []
    crops_quant = []
    crops_order_sub_cost = []
    ord_id_cr = []
    ord_id_fr = []
    items = table_order.scan(
        FilterExpression = Attr('email').eq(request.session['email']) & Attr('is_purchased').eq(False)
    )
    for i in crops['Items']:
        for j in items['Items']:
            if Decimal(i['crop_id'])==j['crop_id'] and j['type']=='crops':
                crops_quant.append(j['quantity'])
                crops_order_sub_cost.append(int(j['quantity'])*int(i['cost']))
    for i in ferts['Items']:
        for j in items['Items']:
            if Decimal(i['fertilizer_id'])==j['crop_id'] and j['type']=='fertilizer':
                crops_quant.append(j['quantity'])
                crops_order_sub_cost.append(int(j['quantity'])*int(i['cost']))

    for i in range(len(items['Items'])):
        if items['Items'][i]['type']=='crops':
            ord_id_cr.append(items["Items"][i]['crop_id'])
    for i in range(len(items['Items'])):
        if items['Items'][i]['type']=='fertilizer':
            ord_id_fr.append(items["Items"][i]['crop_id'])
    for j in crops['Items']:
        for k in ord_id_cr:
            if j['crop_id']==str(k):
                crops_ordered_images.append(j['image_link'])
                crops_ordered_names.append(j['name'])
                crops_ordered_cost.append(j['cost'])
                crops_ava.append(j['stock'])
    for j in ferts['Items']:
        for k in ord_id_fr:
            if j['fertilizer_id']==str(k):
                crops_ordered_images.append(j['img_url'])
                crops_ordered_names.append(j['fertilizer_name'])
                crops_ordered_cost.append(j['cost'])
                crops_ava.append(j['quantity'])

    total_cost = 0
    for i in crops_order_sub_cost:
        total_cost += i
    total_crops_ordered = zip(crops_ordered_names,crops_ordered_images,crops_ordered_cost,crops_ava,crops_order_sub_cost,crops_quant)
    context = {
        'total':total_crops_ordered,
        'total_cost':total_cost
    }
    return render(request,'shopping_cart/cart.html',context)

def buyingpage(request):
    if not is_loggedin(request):
        return redirect('home')
    else:

        dynamodb=boto3.resource('dynamodb')
        crop_table=dynamodb.Table('cropinfo')
        order_table = dynamodb.Table('Order')

        responses = order_table.scan(
            FilterExpression = Attr('email').eq(request.session['email']) & Attr('is_purchased').eq(False)
        )
        order_ids_cr = []
        order_ids_fr = []
        for i in responses['Items']:
            if i['type']=='crops':
                order_ids_cr.append(str(i['crop_id']))
            if i['type']=='fertilizer':
                order_ids_fr.append(str(i['crop_id']))
        crop_table_elements=crop_table.scan()['Items']
        crop_id = []
        crop_name=[]
        crop_cost=[]
        crop_amount=[]
        crop_image_link=[]

        for i in range(len(crop_table_elements)):
            crop_id.append(crop_table_elements[i]['crop_id'])
            crop_name.append(crop_table_elements[i]['name'])
            crop_cost.append(crop_table_elements[i]['cost'])
            crop_amount.append(crop_table_elements[i]['stock'])
            crop_image_link.append(crop_table_elements[i]['image_link'])

        crop_info=zip(crop_id,crop_name,crop_cost,crop_amount,crop_image_link)
        context={
            'crop_info':crop_info,
            'order_ids':order_ids_cr
        }
        return render(request,'shopping_cart/shop.html',context)


def delete_from_cart(request,item_name):
    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table('Order')
    crop_table = dynamodb.Table('cropinfo')
    fert_table = dynamodb.Table('fertilizer_info')
    responses = crop_table.scan(
        FilterExpression = Attr('name').eq(item_name)
    )
    responses_fert = fert_table.scan(
        FilterExpression = Attr('fertilizer_name').eq(item_name)
    )
    # if responses
    try:
        crop_id = responses['Items'][0]['crop_id']
        cur_stock = responses['Items'][0]['stock']
        order_quan = table.scan(
            FilterExpression = Attr('crop_id').eq(Decimal(crop_id)) & Attr('email').eq(request.session['email'])
        )['Items'][0]['quantity']
        print('here')

        crop_table.update_item(
            Key={
                'crop_id': crop_id
            },
            UpdateExpression="set stock = :r",
            ExpressionAttributeValues={
                ':r': int(cur_stock) + int(order_quan),
            },
            ReturnValues="UPDATED_NEW"
        )
    except:
        crop_id = responses_fert['Items'][0]['fertilizer_id']
        cur_stock = responses_fert['Items'][0]['quantity']
        order_quan = table.scan(
            FilterExpression = Attr('crop_id').eq(Decimal(crop_id)) & Attr('email').eq(request.session['email'])
        )['Items'][0]['quantity']
        fert_table.update_item(
            Key={
                'fertilizer_id': crop_id
            },
            UpdateExpression="set quantity = :r",
            ExpressionAttributeValues={
                ':r': int(cur_stock) + int(order_quan),
            },
            ReturnValues="UPDATED_NEW"

farmup/shopping_cart/templates/shopping_cart/cart.html
{% extends 'registration/base.html' %}
{% load static %}

{% block head %}
        <link rel="stylesheet" href="{% static 'homepage/css/home-1-style.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/fonts/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/fonts/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/slick.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/animation.aos.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/timeline.css' %}">

    <link rel="stylesheet" href="{% static 'homepage/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/responsive.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'cart/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'cart/font-awesome.min.css' %}">
    <title>Cart</title>
    {#        <link href="https://fonts.googleapis.com/css2?family=Baloo+Da+2:wght@600&display=swap" rel="stylesheet">#}

    <style>

    </style>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Quickdev">
    <meta name="theme-color" content="#EEC344">

    <!-- ==============================================
    FAVICON
    =============================================== -->
    {#    <link rel="shortcut icon" href="{% static 'homepage/img/master/favicon.png' %}">#}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->


    <!-- ==============================================
    CSS
    =============================================== -->
{% endblock %}

{% block body %}

    <div class="container">
        {% csrf_token %}
        <table id="cart" class="table table-hover table-condensed">
            <thead>
            <tr>
                <th style="width:50%">Product</th>
                <th style="width:10%">Price</th>
                <th style="width:8%">Quantity</th>
                <th style="width:22%" class="text-center">Subtotal</th>
                <th style="width:10%"></th>
            </tr>
            </thead>
            <tbody>

            {% for crops_ordered_names,crops_ordered_images,crops_ordered_cost,crops_ava,crops_order_sub_cost,crops_quant in total %}
                <tr>
                    <td data-th="Product">
                        <div class="row">
                            <div class="col-sm-2 hidden-xs"><img src="{{ crops_ordered_images }}" alt="..." class="img-responsive"/></div>
                            <div class="col-sm-10">
                                <h4 class="nomargin">{{crops_ordered_names}}</h4>
                                <p>Available amount: {{crops_ava}}</p>
                            </div>
                        </div>
                    </td>
                    <td data-th="Price" ><h4 class="nomargin">{{crops_ordered_cost}}</h4></td>
                    <td data-th="Quantity">
                        {#<input type="number" class="form-control text-center" data-type="quan"  min="1" max="{{crops_ava}}" >#}
                        <a href="{% url 'shopping_cart:increase' crops_ordered_names crops_quant 'add' %}"><i class="fas fa-plus ml-2"></i></a>

                        <h4 >{{crops_quant}}</h4>
                <a href="{% url 'shopping_cart:increase' crops_ordered_names crops_quant 'minus' %}"><i class="fas fa-minus mr-2"></i></a>

                    </td>
                    <td data-th="Subtotal" class="text-center" >
                        <h4 class="nomargin">{{crops_order_sub_cost}}</h4>

                    </td>
                    <td class="actions" data-th="">
                        <a href="{% url 'shopping_cart:delete_item' crops_ordered_names%}">
                            <button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <br>
            <form action="{% url 'shopping_cart:checkout' %}" method="post">
                {% csrf_token %}


                <tr>

                    <td><a href="{% url 'shopping_cart:buyingpage' %}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
                    <td colspan="2" ></td>

                    <td class="hidden-xs text-center"><strong>Total {{ total_cost }}</strong> <input type="hidden"  id="amounts"  value="{{ total_cost }}" name="amounts"> </td>
                    <td> </td>
                </tr>
                <tr>

                </tr>

                <table style="width:100%">
                    <tr>
                        <td>
                            <label class="label-input100" for="add1">Address Line1</label>
                            <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                                <input id="add1" class="input100" type="text" name="Address1" placeholder="Eg. Flat No 111, XYZ Cross Road ">
                            </div>
                        </td>

                        <td>
                            <label class="label-input100" for="add2">Address Line2</label>
                            <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                                <input id="add2" class="input100" type="text" name="Address2" placeholder="Eg. Flat No 111, XYZ Cross Road ">
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="label-input100" for="state" >State</label>
                            <div class="wrap-input100" >
                                <input id="state" class="input100" type="text" name="state" placeholder="Telangana" >
                                <span class="focus-input100"></span>
                            </div>
                        </td>
                        <td>
                            <label class="label-input100" for="city" >City</label>
                            <div class="wrap-input100" >
                                <input id="city" class="input100" type="text" name="city" placeholder="Hyderabad" >
                                <span class="focus-input100"></span>
                            </div>
                        </td>

                    </tr>
                    <tr>
                        <td>
                            <label class="label-input100" for="pincode" >Pincode</label>
                            <div class="wrap-input100" >
                                <input id="pincode" class="input100" type="text" name="pincode" placeholder="Eg. 507372" >
                                <span class="focus-input100"></span>
                            </div>
                        </td>


                    </tr>

                </table>
                {#                    <td><input  class="btn btn-success btn-block" type="submit" value="Checkout"> </td>#}
                <div class="container-contact100-form-btn">
                    <input type="submit" value="checkout" class="contact100-form-btn">
                </div>

            </form>
        </table>

    </div>

    <!-- ==============================================
JAVASCRIPTS
=============================================== -->
    <script src="{% static 'homepage/js/plugins.js' %}"></script>
    <script src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'homepage/js/agrom.js' %}"></script>
    {% comment %}
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','../../../www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-101241150-1', 'auto');
    ga('send', 'pageview');
  </script>  {% endcomment %}
{% endblock %}

farmup/shopping_cart/templates/shopping_cart/pandas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
 form{
     width: 70%;
	 margin-top: 0;
	 font-weight: 400;
	 text-align: center;
}
 form #debt-amount-slider {
	 display: flex;
	 flex-direction: row;
	 align-content: stretch;
	 position: relative;
	 width: 100%;
	 height: 50px;
	 user-select: none;
}
 form #debt-amount-slider::before {
	 content: " ";
	 position: absolute;
	 height: 2px;
	 width: 100%;
	 width: calc(100% * (4 / 5));
	 top: 50%;
	 left: 50%;
	 transform: translate(-50%, -50%);
	 background: #000;
}
 form #debt-amount-slider input, form #debt-amount-slider label {
	 box-sizing: border-box;
	 flex: 1;
	 user-select: none;
	 cursor: pointer;
}
 form #debt-amount-slider label {
	 display: inline-block;
	 position: relative;
	 width: 20%;
	 height: 100%;
	 user-select: none;
}
 form #debt-amount-slider label::before {
	 content: attr(data-debt-amount);
	 position: absolute;
	 left: 50%;
	 padding-top: 10px;
	 transform: translate(-50%, 45px);
	 font-size: 14px;
	 letter-spacing: 0.4px;
	 font-weight: 400;
	 white-space: nowrap;
	 opacity: 0.85;
	 transition: all 0.15s ease-in-out;
}
 form #debt-amount-slider label::after {
	 content: " ";
	 position: absolute;
	 left: 50%;
	 top: 50%;
	 transform: translate(-50%, -50%);
	 width: 30px;
	 height: 30px;
	 border: 2px solid #000;
	 background: #fff;
	 border-radius: 50%;
	 pointer-events: none;
	 user-select: none;
	 z-index: 1;
	 cursor: pointer;
	 transition: all 0.15s ease-in-out;
}
 form #debt-amount-slider label:hover::after {
	 transform: translate(-50%, -50%) scale(1.25);
}
 form #debt-amount-slider input {
	 display: none;
}
 form #debt-amount-slider input:checked + label::before {
	 font-weight: 800;
	 opacity: 1;
}
 form #debt-amount-slider input:checked + label::after {
	 border-width: 4px;
	 transform: translate(-50%, -50%) scale(0.75);
}
 form #debt-amount-slider input:checked ~ #debt-amount-pos {
	 opacity: 1;
}
 form #debt-amount-slider input:checked:nth-child(1) ~ #debt-amount-pos {
	 left: 10%;
}
 form #debt-amount-slider input:checked:nth-child(3) ~ #debt-amount-pos {
	 left: 30%;
}
 form #debt-amount-slider input:checked:nth-child(5) ~ #debt-amount-pos {
	 left: 50%;
}
 form #debt-amount-slider input:checked:nth-child(7) ~ #debt-amount-pos {
	 left: 70%;
}
 form #debt-amount-slider input:checked:nth-child(9) ~ #debt-amount-pos {
	 left: 90%;
}
 form #debt-amount-slider #debt-amount-pos {
	 display: block;
	 position: absolute;
	 top: 50%;
	 width: 12px;
	 height: 12px;
	 background: #000;
	 border-radius: 50%;
	 transition: all 0.15s ease-in-out;
	 transform: translate(-50%, -50%);
	 border: 2px solid #fff;
	 opacity: 0;
	 z-index: 2;
}
 form:valid #debt-amount-slider input + label::before {
	 transform: translate(-50%, 45px) scale(0.9);
	 transition: all 0.15s linear;
}
 form:valid #debt-amount-slider input:checked + label::before {
	 transform: translate(-50%, 45px) scale(1.1);
	 transition: all 0.15s linear;
}
 form + button {
	 display: block;
	 position: relative;
	 margin: 56px auto 0;
	 padding: 10px 20px;
	 appearance: none;
	 transition: all 0.15s ease-in-out;
	 font-family: inherit;
	 font-size: 24px;
	 font-weight: 600;
	 background: #fff;
	 border: 2px solid #000;
	 border-radius: 8px;
	 outline: 0;
	 user-select: none;
	 cursor: pointer;
}
 form + button:hover {
	 background: #000;
	 color: #fff;
}
 form + button:hover:active {
	 transform: scale(0.9);
}
 form + button:focus {
	 background: #4caf50;
	 border-color: #4caf50;
	 color: #fff;
	 pointer-events: none;
}
 form + button:focus::before {
	 animation: spin 1s linear infinite;
}
 form + button::before {
	 display: inline-block;
	 width: 0;
	 opacity: 0;
	 content: "\f3f4";
	 font-family: "Font Awesome 5 Pro";
	 font-weight: 900;
	 margin-right: 0;
	 transform: rotate(0deg);
}
 form:invalid + button {
	 pointer-events: none;
	 opacity: 0.25;
}
 @keyframes spin {
	 from {
		 transform: rotate(0deg);
		 width: 24px;
		 opacity: 1;
		 margin-right: 12px;
	}
	 to {
		 transform: rotate(360deg);
		 width: 24px;
		 opacity: 1;
		 margin-right: 12px;
	}
}

    </style>
</head>
<body>
	<form action="/p/quote.php" method="GET">
		<h1 id="form-title">Select Debt Amount</h1>
		<div id="debt-amount-slider">
			<input type="radio" name="debt-amount" id="1" value="1" required>
			<label for="1" data-debt-amount="< $10k"></label>
			<input type="radio" name="debt-amount" id="2" value="2" required>
			<label for="2" data-debt-amount="$10k-25k"></label>
			<input type="radio" name="debt-amount" id="3" value="3" required>
			<label for="3" data-debt-amount="$25k-50k"></label>
			<input type="radio" name="debt-amount" id="4" value="4" required>
			<label for="4" data-debt-amount="$50k-100k"></label>
			<input type="radio" name="debt-amount" id="5" value="5" required>
			<label for="5" data-debt-amount="$100k+"></label>
			<div id="debt-amount-pos"></div>
		</div>
	</form>

</body>
</html>

farmup/shopping_cart/templates/shopping_cart/sellingpage.html
<html>
<body>
    <h1>Reached this page</h1>
</body>
</html>