farmup/farmerandlandlord/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include,path
from . import views
app_name = "farmerandlandlord"

urlpatterns = [
    #path('admin/', admin.site.urls),
    url('^$',views.farmersearch,name='farmersearch'),
    url('^filterfarmer/',views.filterfarmer,name='filterfarmer'),
    # url('^landlordsearch/',views.landlordsearch),
    path('dashboardlandlord/',views.dashboardlandlord,name='dashboardlandlord'),
    path('dashboardfarmer/',views.dashboardfarmer,name='dashboardfarmer'),
    url('^formaddland/',views.formaddland,name='formaddland'),
    url('^addland/',views.addland,name='addland'),
    path('formeditland/<str:land_id>/',views.formeditland,name='formeditland'),
    path('editland/<str:land_id>/',views.editland,name='editland'),
    path('acceptrequest/<str:land_id>/<str:user_id>/<str:username>/',views.acceptrequest,name='acceptrequest'),
    url('^landlordviewrequest/',views.landlordviewrequest,name='landlordviewrequest'),
    # path('infoland/<str:land_id>/',views.infoland,name='infoland'),
    path('leaveland/<str:lwg>/',views.leaveland,name='leaveland'),
    path('deleteland/<str:land_id>/',views.deleteland,name='deleteland'),
    path('farmerrequest/<str:land_id>/<str:user_id>/',views.farmerrequest,name='farmerrequest'),
    path('tofarm',views.tofarm,name="tofarm"),
    path('addcrop/<id>',views.addcrop,name="addcrop"),
    path('tofarm_map/<id>',views.tofarm_map,name="tofarm_map")

]

farmup/farmup/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from registration import views
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('landing/',views.dashboard,name='landing'),
    path('registration/',include(('registration.urls','registration'))),
    path('test',views.test,name='test'),
    path('crop_selling/',include('shopping_cart.urls')),
    path('geo_search/',include('geosearch.urls')),
    path('credits/',include('credits.urls')),
    path('tracking/',include('tracking.urls')),
    path('fertilizer_shop/',include('fertilizer_shop.urls')),
    path('farmerandlandlord/',include('farmerandlandlord.urls'))
]+ static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

farmup/geosearch/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
from django.conf.urls import url
app_name = "geosearch"

urlpatterns = [
    path('map_search/',views.gmaps,name='map_search'),
    path('get_address/',views.get_address,name="get_address")
    ]

farmup/farmerandlandlord/models.py
from django.db import models

# Create your models here.

farmup/farmerandlandlord/views.py
# Create your views here.
from django.shortcuts import render
import boto3
from boto3.dynamodb.conditions import Key, Attr
from django.http import HttpResponse
import hashlib
from django.shortcuts import render, redirect
from geopy.geocoders import Nominatim
from registration.login_required import is_loggedin

#For Pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

#from rest_framework.response import Response

#For storing image
from django.core.files.storage import FileSystemStorage

import random

def farmersearch(request):
	#land_area=250
	if request.method=="POST":
		if request.POST.get('wages_description') !='':
			wages_description=int(request.POST.get('wages_description'))
		else:
			wages_description=None
		if request.POST.get('land_pin_code') !='':
			land_pin_code=request.POST.get('land_pin_code')
		else:
			land_pin_code=None

		
		#isa=True
		type_of_crop=request.POST.get('type_of_crop')
		dynamodb = boto3.resource('dynamodb')
		
		email=request.session['email']
		table=dynamodb.Table('user')
		response=table.scan(FilterExpression=Attr('email').eq(email))
		user_id=response['Items'][0]['farmer_id']
		table=dynamodb.Table('LandInfo')
		"""uid=table.scan(AttributesToGet=['username'])
		uid=uid['Items']
		flag=0
		s=[]
		for i in range(len(uid)): 
			response = table.scan(FilterExpression=Attr('email').eq(email) & Attr('username').eq(uid[i]['username']) & Attr('password').eq(password) & Attr('is_active').eq(isa))
			if len(response['Items'])> 0:
			#print(uid[i]['username'])
				flag=1
				if response['Items'] not in s:
					s.append(response['Items'])
		#print(s)
		if flag==0:
			print(response)
		"""
		#print(table.scan(AttributesToGet=['username']))
		is_active=True
		#user_id="1e25388fde8290dc286a6164fa2d97e551b53498dcbf7bc378eb1f178"
		


		if land_pin_code !=None and type_of_crop !="" and wages_description !=None:
			response = table.scan(FilterExpression= Attr('wages_description').gt(wages_description-1) & Attr('type_of_crop').eq(type_of_crop) & Attr('land_pin_code').eq(land_pin_code))
		elif land_pin_code !=None and type_of_crop !="":
			response = table.scan(FilterExpression= Attr('type_of_crop').eq(type_of_crop) & Attr('land_pin_code').eq(land_pin_code))
		elif type_of_crop !="" and wages_description !=None:
			response = table.scan(FilterExpression= Attr('wages_description').gt(wages_description-1) & Attr('type_of_crop').eq(type_of_crop))
		elif land_pin_code !=None and wages_description !=None:
			response = table.scan(FilterExpression= Attr('wages_description').gt(wages_description-1) &  Attr('land_pin_code').eq(land_pin_code))
		elif land_pin_code!=None:
			response = table.scan(FilterExpression= Attr('land_pin_code').eq(land_pin_code))
		elif type_of_crop!="":
			response = table.scan(FilterExpression= Attr('type_of_crop').eq(type_of_crop))
		elif wages_description!=None:
			response = table.scan(FilterExpression= Attr('wages_description').gt(wages_description-1))
		else:
			response=table.scan()
		#print(wages_description)
		#print(land_pin_code)
		#print(type_of_crop)
		d={}
		for i in range(len(response['Items'])):
			lid=response['Items'][i]['land_id']
			toc=response['Items'][i]['type_of_crop']
			wd=response['Items'][i]['wages_description']
			lpc=response['Items'][i]['land_pin_code']
			la=response['Items'][i]['land_area']
			tos=response['Items'][i]['type_of_soil']
			#print(wd)
			d[i]={'lid':lid,'toc':toc,'wd':wd,'lpc':lpc,'la':la,'tos':tos,'uid':user_id}
		#print(d)
		return render(request,'farmerandlandlord/displayland.html',{'d':d})

def filterfarmer(request):  
	return render(request,"farmerandlandlord/farmersearch.html") 
def farmerrequest(request,land_id,user_id):
	dynamodb = boto3.resource('dynamodb')
	table=dynamodb.Table('FarmerRequest')
	table2=dynamodb.Table('FarmerInfo')
	response=table2.scan(FilterExpression=Attr('farmer_id').eq(user_id))
	print(user_id)
	print(response)
	if response['Count']==0 or response['Items'][0]['land_working']=="":
		table.put_item(Item={
						"user_id":user_id,
						"land_id":land_id
					})
	return redirect('farmerandlandlord:dashboardfarmer')
def acceptrequest(request,land_id,user_id,username):
	dynamodb = boto3.resource('dynamodb')
	table=dynamodb.Table('FarmerInfo')
	response=table.scan(FilterExpression=Attr('farmer_id').eq(user_id))
	if response['Count']==0:
		table.put_item(Item={
						"farmer_id":user_id,
						"username":username,
						"lands_worked":{0},
						"land_working":land_id
					})
	if response['Count']==1:
		table.put_item(Item={
						"farmer_id":user_id,
						"username":username,
						"lands_worked":response['Items'][0]['lands_worked'],
						"land_working":land_id
					})

	table=dynamodb.Table('FarmerRequest')
	response=table.scan(FilterExpression= Attr('user_id').eq(user_id))
	for i in range(response['Count']):
		land_id=response['Items'][i]['land_id']
		table.delete_item(
			Key={
			'user_id':user_id,
			'land_id':land_id
			})
	table=dynamodb.Table('LandInfo')
	response=table.scan(FilterExpression= Attr('land_id').eq(land_id))
	if response['Items'][0]['farmers_working']=={0}:
		a=set()
		b={user_id}
		table.put_item(Item={
					  "is_active": response['Items'][0]['is_active'],
					  "land_area": response['Items'][0]['land_area'],
					  "land_id": response['Items'][0]['land_id'],
					  "land_pin_code": response['Items'][0]['land_pin_code'],
					  "type_of_crop": response['Items'][0]['type_of_crop'],
					  "type_of_soil": response['Items'][0]['type_of_soil'],
					  "wages_description": int(response['Items'][0]['wages_description']),
					  "latitude": response['Items'][0]['latitude'],
					  "longitude": response['Items'][0]['longitude'],
					  "city":response['Items'][0]['city'],
					  "state":response['Items'][0]['state'],
					  "farmers_working":a|b
					})
	else:
		a={response['Items'][0]['farmers_working']}
		b={user_id}
		table.put_item(Item={
					  "is_active": response['Items'][0]['is_active'],
					  "land_area": response['Items'][0]['land_area'],
					  "land_id": response['Items'][0]['land_id'],
					  "land_pin_code": response['Items'][0]['land_pin_code'],
					  "type_of_crop": response['Items'][0]['type_of_crop'],
					  "type_of_soil": response['Items'][0]['type_of_soil'],
					  "wages_description": int(response['Items'][0]['wages_description']),
					  "latitude": response['Items'][0]['latitude'],
					  "longitude": response['Items'][0]['longitude'],
					  "city":response['Items'][0]['city'],
					  "state":response['Items'][0]['state'],
					  "farmers_working":a|b
					})

				
	return redirect('farmerandlandlord:dashboardlandlord')

def formaddland(request):  
	return render(request,"farmerandlandlord/formaddland.html")


def addland(request):
	dynamodb = boto3.resource('dynamodb')
	table=dynamodb.Table('LandInfo')
	response=table.scan()
	if request.method=="POST":
		if table.scan()['Count']==0:
			land_id=table.scan()['Count'] + 1
		else:
			m=0
			for i in range(response['Count']):
				if int(response['Items'][i]['land_id'])>m:
					m=int(response['Items'][i]['land_id'])
			land_id=m+1
		wages=request.POST.get('wages_description')
		type_of_crop=request.POST.get('type_of_crop')
		type_of_soil=request.POST.get('type_of_soil')
		land_area=request.POST.get('land_area')
		land_pin_code=request.POST.get('land_pin_code')
		latitude=request.POST.get('lat')
		longitude=request.POST.get('long')
		info=request.POST.get('info')

		is_active=False
	
		img_url=["https://mediacdn.99acres.com/media1/11509/11/230191522T-1590937910302.jpg",
			"https://mediacdn.99acres.com/media1/9524/11/190491195T-1568192438225.jpeg",
			"https://mediacdn.99acres.com/media1/9524/7/190487543T-1568191830940.jpeg",
			"https://mediacdn.99acres.com/media1/11913/9/238269165T-1595408941546.jpg",
			"https://mediacdn.99acres.com/media1/11486/3/229723778T-1590480794237.jpg",
			"https://mediacdn.99acres.com/media1/11509/11/230191522T-1590937910302.jpg",
			"https://mediacdn.99acres.com/media1/7827/16/156556115T-1569598029091.jpeg",
			"https://mediacdn.99acres.com/media1/11024/8/220488103O-1581953983240.jpeg",
			"https://mediacdn.99acres.com/media1/11556/18/231138858T-1591705705752.jpg",
			"https://mediacdn.99acres.com/media1/11564/6/231286302T-1591791449389.jpg"
			]
		
		geolocator = Nominatim(user_agent="bobo")
		location = geolocator.reverse(str(latitude) +","+ str(longitude),exactly_one=True)
		address = location.raw['address']
		city = address.get('city','')
		state = address.get('state','')
		pin = address.get('postcode','')
		if not city:
			city = address.get('village','')
		if address and city:
			table.put_item(Item={
			  "is_active": is_active,
			  "land_area": land_area,
			  "land_id": str(land_id),
			  "land_pin_code": land_pin_code,
			  "type_of_crop": type_of_crop,
			  "type_of_soil": type_of_soil,
			  "wages_description": int(wages),
			  "latitude": latitude,
			  "longitude": longitude,
			  "city":city,
			  "state":state,
			  "farmers_working":{0},
			  "img_url":random.choice(img_url),
			  "info":info
			})

			email=request.session['email']
			table=dynamodb.Table('user')
			response=table.scan(FilterExpression=Attr('email').eq(email))
			land_lord_id=response['Items'][0]['land_lord_id']
			land_lord_name=response['Items'][0]['username']
			table=dynamodb.Table('Landlord')
			response=table.scan(FilterExpression=Attr('land_lord_id').eq(land_lord_id))
			#land_lord_name=response['Items'][0]['land_lord_name']
			#response=table.scan()
			if response['Count']>0:
				a=response['Items'][0]['lands_owned']
				print(a)
			else:
				a=set()
			b={land_id}
			print(a|b)
			table.put_item(Item={
				"land_lord_id": land_lord_id,
				"land_lord_name":land_lord_name ,
				#"lands_owned":"{" + str(response['Items'][0]['lands_owned'])+"," + str(land_id) + "}"
				"lands_owned":a|b
			})

	
	return redirect('farmerandlandlord:dashboardlandlord')
def formeditland(request,land_id):  

farmup/farmerandlandlord/templates/farmerandlandlord/displayfarmer.html
{% extends 'registration/base.html' %}
{% load static %}
{% block head %}


<style>
.card {
  box-shadow: 5px 10px 18px #888888;
  max-width: 400px;
  margin: auto;
  text-align: center;
  font-family: inherit;
}
.card:hover{
  box-shadow: 10px 10px 5px grey;
}
.title {
  color: grey;
  font-size: 18px;
}
.column {
  float: left;
  width: 40%;
  margin-bottom: 16px;
  padding: 0 8px;
}


button:hover, a:hover {
  opacity: 0.7;
}
.butn-submit {
  display: block;
  margin-top: 32px;
  width: 100%;
  line-height: 50px;
  font-family: inherit;
  background: #008000;
  color: #fff;
  font-size: 16px;
  -webkit-transition: all 0.4s ease;
  -o-transition: all 0.4s ease;
  -moz-transition: all 0.4s ease;
  transition: all 0.4s ease;
}

</style>
{% endblock %}
{% block body %}

<h2 style="text-align:center">Farmer Requests</h2>
{% if d %}
<div class="row">
  {% for key,value in d.items %}
<div class="column">
<div class="card z-depth-5">
  <img src="{% static 'img/farmer.jpg' %}" style="width:100%">
  <ul>
  <p>{{value.un}}</p>
  <p>{{value.ue}}</p>
  <p>{{value.uadd}}</p>
  <p>{{value.uph}}</p>
  <p>{{value.lid}}</p>
  <p>{{value.toc}}</p>
  <p>{{value.tos}}</p>
  <p>{{value.lpc}}</p>
  <p>{{value.la}}</p>
  </ul>

  <a href="{% url 'farmerandlandlord:acceptrequest' value.lid value.uid value.un  %}"><button class="butn-submit" style="font-size:24px">Accept</button></a>
</div>

</div>
{% endfor %}
</div>
{% else %}
<h2 style="text-align:center">No Requests</h2>

{% endif %}

{% endblock %}

farmup/farmerandlandlord/templates/farmerandlandlord/displayland.html
{% extends 'registration/base.html' %}
{% load static %}

{% block head %}
 <link rel="stylesheet" href="{% static 'homepage/css/home-1-styles.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/fonts/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/fonts/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/slick.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/animation.aos.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/timeline.css' %}">

    <link rel="stylesheet" href="{% static 'homepage/css/bootstrap.min.css' %}">    
    <link rel="stylesheet" href="{% static 'homepage/css/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/responsive.css' %}">
   
	    <style type="text/css">
    	.butn-submit {
  display: block;
  margin-top: 32px;
  width: 100%;
  line-height: 50px;
  font-family: inherit;
  background: #008000;
  color: #fff;
  font-size: 16px;
  -webkit-transition: all 0.4s ease;
  -o-transition: all 0.4s ease;
  -moz-transition: all 0.4s ease;
  transition: all 0.4s ease;
}

.butn-submit:hover {
  background: #eb6f00;
}
a{
  color:inherit;
}
.card{
  box-shadow: 5px 10px 18px #888888;
}
.card:hover{
  box-shadow: 10px 10px 5px grey;
}
    </style>
  {% endblock %}

	{% block body %}

	<div class="row">
		{% for key, value in d.items %}
	<a href="{% url 'farmerandlandlord:infoland' value.lid %}">
    <div class="col-sm-3">
      <div class="card large z-depth-5">
        <div class="card-image" style=" ">
          <img src="{% static 'img/paddy.jpg ' %}">

        </div>
        <div class="card-body">

		<ul>
			<li>{{value.toc}}</li>
			<li>{{value.wd}}</li>
			<li>{{value.lpc}}</li>
			<li>{{value.la}}</li>
			<li>{{value.tos}}</li>

	    </ul>

        </div>
        <div>
        <a href="{% url 'farmerandlandlord:farmerrequest' value.lid value.uid %}">
	    <button class="butn-submit" style="font-size:24px">Contact</button>
	    </a>
	    </div>

      </div>
    </div>
    </a>
    {% endfor %}

  </div>
	{% endblock %}

farmup/farmerandlandlord/templates/farmerandlandlord/farmersearch.html
{% extends 'registration/base.html' %}
{% load static %}
{% block head %}
    <!-- Required meta tags-->
    
    
    <!-- Title Page-->
    

    <!-- Icons font CSS-->
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    
    <!-- Main CSS-->
    <link href="{% static 'form.css' %}" rel="stylesheet" media="all">
     <link rel="stylesheet" href="{% static 'homepage/css/home-1-styles.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/fonts/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/fonts/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/slick.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/animation.aos.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/timeline.css' %}">

    <link rel="stylesheet" href="{% static 'homepage/css/bootstrap.min.css' %}">    
    <link rel="stylesheet" href="{% static 'homepage/css/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/responsive.css' %}">
   
{% endblock %}

{% block body %}
    <div class="page-wrapper bg-color-1 p-t-165 p-b-100">
        <div class="wrapper wrapper--w680">
            <div class="card card-2">
                <div class="card-body">
                    <ul class="tab-list">
                        <li class="tab-list__item active">
                            <a class="tab-list__link" href="#tab1" data-toggle="tab">Filter</a>
                        </li>
                        
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab1">
                            <form method="POST" action="{% url 'farmerandlandlord:farmersearch' %}">
                                {% csrf_token %}
                                <div class="input-group">
                                    <label class="label">type of crop</label>
                                    <input class="input--style-1" type="text" name="type_of_crop" placeholder="enter crop name">
                                </div>
                                <div class="input-group">
                                    <label class="label">pincode</label>
                                    <input class="input--style-1" type="text" name="land_pin_code" placeholder="please enter only 6 digits">
                                </div>
                                <div class="input-group">
                                    <label class="label">wages</label>
                                    <input class="input--style-1" type="text" name="wages_description" placeholder="enter money in rupees" >
                                </div>
                                
                                
                                   
                                <button class="btn-submit" type="submit">search</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
{% endblock %}
<!-- end document-->

farmup/farmerandlandlord/templates/farmerandlandlord/tofarm.html
{% extends 'registration/base.html' %}
{% load staticfiles %}

  {% block head%}
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'tofarm.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {% endblock %}
  
  
  {% block body%}

      <div class="search-container">
        <form action>
          <input type="text" placeholder="Search.." name="search">
          <button  type="submit"><i class="fa fa-search fa-2x"></i></button>
          </form>
      </div>
      
        <div class="filters" style="float: left;width: 23%;height:100%;padding: 2%;">
            <div class="row">
                <div class="col-12" id="filter">
                    <form class="form1" action="{% url 'farmerandlandlord:tofarm' %}" method="post">
                        {% csrf_token %}
                        <h5> Wages/Day </h5>
                        <hr>
                        <input type="checkbox" name="a" value="<100"> &ltRs.100 <br>
                        <input type="checkbox" name="a" value="100-200"> Rs.100 - Rs.200<br>
                        <input type="checkbox" name="a" value="200-300"> Rs.200 - Rs.300<br>
                        <input type="checkbox" name="a" value="300-400"> Rs.300 - Rs.400<br>
                        <input type="checkbox" name="a" value=">400"> &gtRs.400<br><br>
                        <h5> Pin Code </h5>
                        <hr>
                        <input type="text" name="pincode" placeholder="pincode"> <br><br>
                        <h5> Crops </h5>
                        <hr>
                        {% for crop in crops %}
                        <input type="checkbox" name="c" value={{ crop }}> {{ crop }}<br>
                        {% endfor %}
                        <br>
                        <input type="submit"  class="btn btn-info" style="width: 100%;">
                     </form> 

                     <form action="{% url 'geosearch:get_address' %}">
                        <input type="submit"  class="btn btn-success" value="Geo Search" style="width: 100%;">
                     </form>  
                
                </div>
            </div>
        </div>
       
        <div class="information" style="float: left;width: 70%;padding: 2%;position:relative;overflow-y:scroll;height:650px">
            
            {% for land in l_info%}
            <div class="landinfo">
                <div class="row" id="land" >
                    <div class="col-4" style="padding: 2%;">
                        <img class="image" src={{ land.img_url }} alt="" height="60%" width="80%">
                    </div>
                    <div class="col-8">
                        <div class="row">
                            <div class="col-5" style="padding: 2%;padding-top: 5%;">
                                <h4>{{ land.city }}<br>{{ land.state }}</h4>
                                <p>
                                    Land Area : {{ land.land_area }}
                                </p>
                            </div>
                            <div class="col-5" style="padding: 2%;padding-top: 5%;">
                                <div>
                                    <ul>
                                        <li>
                                            Soil Type : {{ land.type_of_soil }}
                                        </li>
                                        <li>
                                            Crop Grown : {{ land.type_of_crop }}
                                        </li>
                                        <li>
                                            Wage/day : {{ land.wages_description }}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-2" style="padding: 2%;padding-top: 8%;">
                                <button type="button" class="btn btn-primary">Work</button>
                            </div>
                        </div>
                        <div class="row" style="padding: 2%;padding-top: 3%;">
                            It is a long established fact that a reader 
                            will be distracted by the readable content of 
                            a page when looking at its layout. The point of 
                            using Lorem Ipsum is that it has a more-or-less 
                            normal distribution of letters, as opposed to 
                            'Content here, content here', making it look .
                            a page when looking at its layout. The point of 
                            using Lorem Ipsum is that it has a more-or-less 
                            normal distribution of letters, as opposed to 
                            'Content here, content here', making it look .
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        
        </div>   

     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="bootstrap4/js/bootstrap.min.js"></script>
  {% endblock %}