farmup/farmup/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from registration import views
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('landing/',views.dashboard,name='landing'),
    path('registration/',include(('registration.urls','registration'))),
    path('test',views.test,name='test'),
    path('crop_selling/',include('shopping_cart.urls')),
    path('geo_search/',include('geosearch.urls')),
    path('credits/',include('credits.urls')),
    path('tracking/',include('tracking.urls')),
    path('fertilizer_shop/',include('fertilizer_shop.urls')),
    path('farmerandlandlord/',include('farmerandlandlord.urls'))
]+ static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

farmup/fertilizer_shop/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views

app_name = "fertilizer_shop"


urlpatterns = [
    path('addfertilizer',views.addfertilizer,name="addfertilizer"),
    path('createnew',views.createnew,name="createnew"),
    path('shop',views.shop,name="shop"),
    path('iteminfo/<id>',views.iteminfo,name='iteminfo')
]

farmup/shopping_cart/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views

app_name = "shopping_cart"


urlpatterns = [
    path('buyingportal/', views.buyingpage, name='buyingpage'),
    path('addCropElements/', views.addCropElements, name='addCropElements'),
    path('', views.addCropElements, name="add_to_cart"),
    path('buyingportal/cart/',views.checkout,name="cart"),
    path('deleteitems/<item_name>',views.delete_from_cart,name="delete_item"),
    path('add',views.add),
    path('buyingportal/checkout/',views.checkout_sub,name='checkout'),
    path('buyingportal/tempcheck/',views.add_items,name='temp'),
    path('search',views.search,name='search'),
    path('increase_quan/<cropname>/<quan>/<oper>',views.change_quantity,name='increase'),

]

farmup/fertilizer_shop/models.py
from django.db import models

# Create your models here.

farmup/fertilizer_shop/views.py
from django.shortcuts import render,redirect,HttpResponse
import boto3
from boto3.dynamodb.conditions import Key, Attr
from decimal import *
# Create your views here.

#For storing images
from django.core.files.storage import FileSystemStorage

#For Pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def addfertilizer(request):

    dynamodb=boto3.resource("dynamodb")
    table=dynamodb.Table("fertilizer_info")
    added=0    

    if request.method=="POST":
        name=request.POST.get("name")
        quantity=request.POST.get("quantity")
        cost=request.POST.get("cost")
        soiltype=request.POST.get("type")
        info=request.POST.get("info")
        physicalform=request.POST.get("phyform")
        perpackquantity=request.POST.get("perpackqty")
        img_file=request.FILES['img_file']

        fs = FileSystemStorage()
        fs.save(img_file.name, img_file)
        s3 = boto3.client('s3')
        bucket = 'farmup-s3'

        file_name = str(img_file)
        key_name = str(img_file)

        s3.upload_file(file_name, bucket, key_name)

        link = "https://s3-ap-south-1.amazonaws.com/{0}/{1}".format(
             bucket,
             key_name)

        id=len(table.scan()["Items"])
        id=str(id+1)

        table.put_item(
            Item={
            "fertilizer_id":id,
            "fertilizer_name":name,
            "quantity":quantity,
            "cost":cost,
            "soiltype":soiltype,
            "info":info,
            "physicalform":physicalform,
            "perpackquantity":perpackquantity,
            "img_url":link
        })

        data={
            "added":1,
            "checker":1,
            "fertilizer_id":id,
            "fertilizer_name":name,
            "quantity":quantity,
            "cost":cost,
            "soiltype":soiltype,
            "info":info,
            "physicalform":physicalform,
            "perpackquantity":perpackquantity,
            "img_url":link
        }
        return render(request,'fertilizer_shop/new_fertilizer.html',context=data)
    data={
        "added":0,
        "checker":1
    }
    return render(request,'fertilizer_shop/new_fertilizer.html',context=data)


def createnew(request):
    return redirect("fertilizer_shop:addfertilizer")

def shop(request):
    dynamodb=boto3.resource("dynamodb")
    table=dynamodb.Table("fertilizer_info")

    information=table.scan()["Items"]

    page = request.GET.get('page', 1)


    if request.method=="POST":
        pricelist=request.POST.getlist("a")
        soillist=request.POST.getlist("b")
        physicalform=request.POST.getlist("c")

        datalist1=[]
        datalist2=[]
        datalist3=[]

        if (len(pricelist)!=0):
            for element in pricelist:
                if("<" in element):
                    for info in information:
                        if int(info["cost"])<100:
                            datalist1.append(info)  
                elif (">" in element):
                    for info in information:
                        if int(info["cost"])>400:
                            datalist1.append(info)
                else:
                    price=element.split("-")
                    low=int(price[0])
                    high=int(price[1])
                    for info in information:
                        if (int(info["cost"])>=low) and (int(info["cost"])<=high) :
                            datalist1.append(info)


        if (len(soillist)!=0):
            for element in soillist:
                for info in information:
                    if (info["soiltype"]==element) :
                        datalist2.append(info)

        if (len(physicalform)!=0):
            for element in physicalform:
                for info in information:
                    if (info["physicalform"]==element) :
                        datalist3.append(info)


        if ((len(pricelist)!=0) and (len(soillist)!=0) and (len(physicalform)!=0)):
            output1=[element1 for element1 in datalist1 for element2 in datalist2 if element1['fertilizer_id']==element2['fertilizer_id']]
            filterOutput=[element1 for element1 in output1 for element2 in datalist3 if element1['fertilizer_id']==element2['fertilizer_id']]
        elif ((len(pricelist)!=0) and (len(soillist)!=0)):
            filterOutput=[element1 for element1 in datalist1 for element2 in datalist2 if element1['fertilizer_id']==element2['fertilizer_id']]
        elif ((len(pricelist)!=0) and (len(physicalform)!=0)):
            filterOutput=[element1 for element1 in datalist1 for element2 in datalist3 if element1['fertilizer_id']==element2['fertilizer_id']]
        elif ((len(soillist)!=0) and (len(physicalform)!=0)):
            filterOutput=[element1 for element1 in datalist2 for element2 in datalist3 if element1['fertilizer_id']==element2['fertilizer_id']]
        elif ((len(pricelist)!=0)):
            filterOutput=datalist1
        elif ((len(soillist)!=0)):
            filterOutput=datalist2
        elif ((len(physicalform)!=0)):
            filterOutput=datalist3
        else:
            filterOutput=information
            

        fertilizer_info=[]

        for item in filterOutput:
            data={
                "fertilizer_id":item["fertilizer_id"],
                "fertilizer_name":item["fertilizer_name"],
                "cost":item["cost"],
                "soiltype":item["soiltype"],
                "img_url":item["img_url"]
            }
            fertilizer_info.append(data)
    
        

        paginator = Paginator(fertilizer_info, 6)
        try:
            fer_info = paginator.page(page)
        except PageNotAnInteger:
            fer_info = paginator.page(1)
        except EmptyPage:
            fer_info = paginator.page(paginator.num_pages)

        context={
            "fer_info":fer_info
        }

        return render(request,'fertilizer_shop/shop.html',context)


    fertilizer_info=[]

    for item in information:
        data={
            "fertilizer_id":item["fertilizer_id"],
            "fertilizer_name":item["fertilizer_name"],
            "cost":item["cost"],
            "soiltype":item["soiltype"],
            "img_url":item["img_url"]
        }
        fertilizer_info.append(data)
    
    

    paginator = Paginator(fertilizer_info, 6)
    try:
        fer_info = paginator.page(page)
    except PageNotAnInteger:
        fer_info = paginator.page(1)
    except EmptyPage:
        fer_info = paginator.page(paginator.num_pages)

    context={
        "fer_info":fer_info
    }
    
    return render(request,'fertilizer_shop/shop.html',context)


def iteminfo(request,id):
    dynamodb=boto3.resource("dynamodb")
    table=dynamodb.Table("fertilizer_info")
    table_order = dynamodb.Table('Order')
    info = table.scan(
            FilterExpression = Attr('fertilizer_id').eq(id)
        )
    is_ordered = table_order.scan(
        FilterExpression = Attr('crop_id').eq(Decimal(id)) & Attr('type').eq('fertilizer')
    )['Items']
    # all_orders = table_order.scan()['Items']
    if is_ordered:
        ordered = True
    else:
        ordered = False
    print(ordered)
    data=info["Items"][0]
    available=int(float(data["quantity"])/float(data["perpackquantity"]))
    print(available)

    if data["physicalform"]=="Solid":
        measure="Kg"
    else:
        measure="L"

    context={
        "fertilizer_id":data["fertilizer_id"],
        "name":data["fertilizer_name"],
        "soiltype":data["soiltype"],
        "price":data["cost"],
        "perpackquantity":data["perpackquantity"],
        "info":data["info"],
        "available":available,
        "measure":measure,
        "img_url":data["img_url"],
        "is_ordered":ordered

    }

    return render(request,'fertilizer_shop/item_info.html',context=context)

farmup/fertilizer_shop/templates/fertilizer_shop/item_info.html
{% extends 'registration/base.html' %}
{% load staticfiles %}


{% block head%}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/new_fertilizer/item_info.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}


{% block body %}

    <div class="description"">
    <div class="info1" style="width:60%;float: left;padding: 2%;">
        <div class="col-12" id="center">
            <img class="dark" src={{ img_url }} style="width:30%">
        </div>
        <div class="write">
            <p>
                <span style="font-weight:bold;font-size:30px">Description</span><br>
                {{ info }}
            </p>
        </div>

    </div>

    <div class="info2" style="width:37%;float: left;">
        <div class="row">
            <div class="col-12">
                <p>
                    <span style="font-weight: bold;font-size: 40px;">{{ name }}</span> <br>
                    <span style="font-size: 15px;">{{perpackquantity}} {{measure}} per pack</span> <br>
                    <span style="font-size: 20px">Available Quantity: {{available}} packs</span> <br>
                    <span style="font-weight: bold;font-size: 25px;color: red;">Rs.{{ price }}</span>-Per Pack <br>
                    <span style="font-weight: bold;font-size: 20px;color: brown;">Soil Type: {{ soiltype }}</span><br>
                    <span style="font-weight: bold;font-size: 20px;color: brown;">Soil Type: {{ fertilizer_id }}</span><br>
                </p>
                {% if not is_ordered %}

                    <form action="{% url 'shopping_cart:add_to_cart' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" value="fertilizer" name="type">
                        <input type="hidden" name="crop_name" value={{name}}>
                        <input type="hidden" name="id" value={{fertilizer_id}}>
                        <div class="input-group input-number-group" style="padding-right: 50%;">
                            <div class="input-group-button">
                                <span class="input-number-decrement">-</span>
                            </div>
                            <input class="input-number" type="number" name="quantity" value="1" min="0" max="1000">
                            <div class="input-group-button">
                                <span class="input-number-increment">+</span>
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-info" style="margin-left: 8%;width: 40%;">Add To Cart</button>
                    </form>

                {% else %}
                    <a href="{% url 'shopping_cart:cart' %}">  <button type="button" class="btn btn-info" style="margin-left: 8%;width: 40%;">Go To Cart</button> </a>

                {% endif %}
            </div>
        </div>
    </div>

    </div>


    <script
            src="https://code.jquery.com/jquery-3.5.1.js"
            integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
            crossorigin="anonymous"></script>

    <script>
        $('.input-number-increment').click(function() {
            var $input = $(this).parents('.input-number-group').find('.input-number');
            var val = parseInt($input.val(), 10);
            $input.val(val + 1);
        });

        $('.input-number-decrement').click(function() {
            var $input = $(this).parents('.input-number-group').find('.input-number');
            var val = parseInt($input.val(), 10);
            if(val===1){
                $input.val(val);
            }
            else{
                $input.val(val - 1);
            }

        })

    </script>

{% endblock %}

farmup/fertilizer_shop/templates/fertilizer_shop/new_fertilizer.html
{% extends 'registration/base.html' %}
{% load staticfiles %}

  {% block head%}
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/new_fertilizer/new_fertilizer.css' %}">
    <style>
      .fertilizer_info{
        background-image: url("{% static 'fertilizer_shop/images/image2.jpg'%}");
        background-size: cover;
        overflow-y:hidden;
        padding-top:2%;
      }
    </style>
  {% endblock %}

  {% block body%}
  <div class="fertilizer_info">
      <section class="services">
        <div class="container">
          <div class="header">
            <h3>New Fertilizer</h3>
          </div>
            <div class="media-object">
                
                <div class="blurb-wrapper-right">
                  <div class="container1">
                  
                  
                  {% if added == checker %}

                      <div class="icon-left" style="float: left">
                        <img  class="icon" src={{img_url}} alt="graph chart">
                      </div>
                      
                      <form action="{% url 'fertilizer_shop:createnew' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                      
                        <div class="group" style="float: right">      
                          <input type="text" required name="quantity" value="{{quantity}}">
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Quantity</label>
                        </div>
                          
                        <div class="group" style="float: right">      
                          <input type="text" required name="name" value={{fertilizer_name}}>
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Name</label>
                        </div>

                        <div class="group" style="float: right">      
                          <input type="text" required name="cost" value={{cost}}>
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Cost</label>
                        </div>

                        <div class="group" style="float: right">      
                          <input type="text" required name="type" value={{soiltype}}>
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Type Of Soil</label>
                        </div>

                        <div class="group" style="float: right">      
                          <input type="text" required name="phyform" value={{physicalform}}>
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Physical Form</label>
                        </div>

                        <div class="group" style="float: right">      
                          <input type="text" required name="perpackqty" value={{perpackquantity}}>
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Per Pack Quantity</label>
                        </div>

                        <div class="group" style="float: left;">      
                          <input type="file" name="img_file" class="btn btn-info">
                        </div>

                        <div class="wrapper">
                          <div class="form-group">
                            <textarea class="form-control rounded-0" id="exampleFormControlTextarea2" rows="8" cols="20" name="info">
                              {{info}} 
                            </textarea>
                          </div>
                        </div>
                    

                        <div style="float: right;padding-bottom: 2%;width:40%;padding-right:20%" >     
                          <input type="submit" value="Another Fertilizer" required class="btn btn-info" >
                        </div>
                        
                      </form>

                    {% else %}
                      <div class="icon-left" style="float: left">
                        <img  class="icon" src="{% static 'images/default_img.png'%}" alt="graph chart">
                      </div>
                      
                      <form action="{% url 'fertilizer_shop:addfertilizer' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                      
                        <div class="group" style="float: right">      
                          <input type="text" required name="quantity">
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Quantity</label>
                        </div>
                          
                        <div class="group" style="float: right">      
                          <input type="text" required name="name">
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Name</label>
                        </div>

                        <div class="group" style="float: right">      
                          <input type="text" required name="cost">
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Cost</label>
                        </div>

                        <div class="group" style="float: right">      
                          <input type="text" required name="type">
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Type Of Soil</label>
                        </div>

                        <div class="group" style="float: right">      
                          <input type="text" required name="phyform">
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Physical Form</label>
                        </div>

                        <div class="group" style="float: right">      
                          <input type="text" required name="perpackqty">
                          <span class="highlight"></span>
                          <span class="bar"></span>
                          <label>Per Pack Quantity</label>
                        </div>

                        <div class="group" style="float: left;">      
                          <input type="file" name="img_file" class="btn btn-info">
                        </div>

                        <div class="wrapper">
                          <div class="form-group">
                            <textarea class="form-control rounded-0" id="exampleFormControlTextarea2" rows="8" cols="20" name="info">
                              Enter Fertilizer Information 
                            </textarea>
                          </div>
                        </div>
                        
                        <div style="float: right;padding-bottom: 2%;width:40%;padding-right:20%" >     
                          <input type="submit" required class="btn btn-info" >
                        </div>
                        
                      </form>
                  {% endif %}
                        
                    
                  </div>
                </div>
            </div>
         

  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="bootstrap4/js/bootstrap.min.js"></script>

  {% endblock %}

farmup/fertilizer_shop/templates/fertilizer_shop/shop.html
{% extends 'registration/base.html' %}
{% load staticfiles %}

  {% block head%}
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/new_fertilizer/shop.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {% endblock %}
  
  
  {% block body%}
      <div class="search-container">
        <form action>
          <input type="text" placeholder="Search.." name="search">
          <button  type="submit"><i class="fa fa-search fa-2x"></i></button>
          </form>
      </div>
      
        <div class="filters" style="float: left;width: 23%;height:100%;padding: 2%;">
            <div class="row">
                <div class="col-12">
                    <form class="form1" action="{% url 'fertilizer_shop:shop' %}" method="post">
                        {% csrf_token %}
                        <h5> Price </h5>
                        <hr>
                        <input type="checkbox" name="a" value="<100"> &ltRs.100 <br>
                        <input type="checkbox" name="a" value="100-200"> Rs.100 - Rs.200<br>
                        <input type="checkbox" name="a" value="200-300"> Rs.200 - Rs.300<br>
                        <input type="checkbox" name="a" value="300-400"> Rs.300 - Rs.400<br>
                        <input type="checkbox" name="a" value=">400"> &gtRs400<br><br>
                        <h5> Type Of Soil </h5>
                        <hr>
                        <input type="checkbox" name="b" value="Black"> Black<br>
                        <input type="checkbox" name="b" value="Red"> Red<br>
                        <input type="checkbox" name="b" value="Alluvial"> Alluvial<br><br>
                        <h5> Fertilizer Type </h5>
                        <hr>
                        <input type="checkbox" name="c" value="Solid"> Soild<br>
                        <input type="checkbox" name="c" value="Liquid"> Liquid<br><br>
                        <input type="submit"  class="btn btn-info" style="width: 100%;">
                     </form>   
                </div>
            </div>
        </div>
       
        <div class="information" style="float: left;width: 70%;padding: 2%;position:relative;">
            <div class="row">
                {% for fer in fer_info %}
                    <div class="col-4">
                        <div class="card" style="width:90%">
                            <img class="card-img-top" src={{fer.img_url}} alt="Card image cap">
                            <div class="card-body">
                                <p class="card-text">
                                <span style="font-weight:bold;font-size:20px">{{fer.fertilizer_name}}</span><br>
                                Soil Type : <span style="font-weight:bold">{{fer.soiltype}}</span><br>
                                <span style="color:red;float:right;font-weight:bold;font-size:20px">Rs.{{fer.cost}}</span>
                                </p>
                                <form action="{% url 'fertilizer_shop:iteminfo' fer.fertilizer_id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary" value="More Info">More Info</button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row" style="display:block;text-align:center">
                <div>
                    {% if fer_info.has_other_pages %}
                    <ul class="pagination" style="width:100%;font-size:30px;padding-left:40%">
                        {% if fer_info.has_previous %}
                        <li style="margin:3%"><a href="?page={{ fer_info.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                        <li class="disabled" style="margin:3%"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in fer_info.paginator.page_range %}
                        {% if fer_info.number == i %}
                            <li class="active" style="margin:3%"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li style="margin:3%"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                        {% endfor %}
                        {% if fer_info.has_next %}
                        <li style="margin:3%"><a href="?page={{ fer_info.next_page_number }}">&raquo;</a></li>
                        {% else %}
                        <li class="disabled" style="margin:3%"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                    {% endif %}
                </div>
            <div>
        </div>   

     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="bootstrap4/js/bootstrap.min.js"></script>
  {% endblock %}