farmup/credits/urls.py
from django.urls import path,re_path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('pending_redeem/',views.pending_redeem,name='pending_redeem'),
    path('verify_sms/',views.verify_sms,name='verify_sms'),
    path('add_balance/',views.add_balance,name='add_balance'),
    # path('', views.HomePageView.as_view(), name='home'),
    path('home/',views.home,name='credits_home'),
    path('config/', views.stripe_config),
    path('create-checkout-session/', views.create_checkout_session),
    path('success/<session_id>/<trans_id>', views.success),
    path('cancelled', views.cancel),
    path('transactions/<par>',views.transactions,name='transactions'),
    path('cancel/',views.redeem_cancel,name="cancel"),
    path('trans_cancel/',views.trans_cancel,name='trans_cancel')

]

farmup/farmup/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from registration import views
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('landing/',views.dashboard,name='landing'),
    path('registration/',include(('registration.urls','registration'))),
    path('test',views.test,name='test'),
    path('crop_selling/',include('shopping_cart.urls')),
    path('geo_search/',include('geosearch.urls')),
    path('credits/',include('credits.urls')),
    path('tracking/',include('tracking.urls')),
    path('fertilizer_shop/',include('fertilizer_shop.urls')),
    path('farmerandlandlord/',include('farmerandlandlord.urls'))
]+ static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

farmup/registration/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
from django.conf.urls import url
app_name = "registration"

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('login_display/',views.login_display,name='login_display'),
    path('register_display/',views.register_display,name='register_display'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',views.activate, name='activate'),
    url(r'verify_reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',views.verify_reset_password, name='verify_reset_password'),
    path('reset_display/',views.reset_display,name='reset_display'),
    path('reset_password/',views.reset_password,name='reset_password'),
    path('save_password/',views.save_password,name='save_password'),
    path('my_profile/',views.display_profile,name='my_profile'),
    path('edit_profile_display',views.display_edit_profile,name='display_edit_profile'),
    path('edit_profile',views.edit_profile,name="edit_profile"),
    path('verify_lands',views.verify_lands,name="verify_lands"),
    url(r'accept_land/(?P<id>[0-9]+)/',views.accept_land,name="accept_land"),
    url(r'reject_land/(?P<id>[0-9]+)/',views.reject_land,name="reject_land")
    ]

farmup/shopping_cart/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views

app_name = "shopping_cart"


urlpatterns = [
    path('buyingportal/', views.buyingpage, name='buyingpage'),
    path('addCropElements/', views.addCropElements, name='addCropElements'),
    path('', views.addCropElements, name="add_to_cart"),
    path('buyingportal/cart/',views.checkout,name="cart"),
    path('deleteitems/<item_name>',views.delete_from_cart,name="delete_item"),
    path('add',views.add),
    path('buyingportal/checkout/',views.checkout_sub,name='checkout'),
    path('buyingportal/tempcheck/',views.add_items,name='temp'),
    path('search',views.search,name='search'),
    path('increase_quan/<cropname>/<quan>/<oper>',views.change_quantity,name='increase'),

]

farmup/tracking/urls.py
from django.urls import path ,include
from django.conf import settings
from . import views

app_name='tracking'
urlpatterns = [
    path('',views.track,name='track'),
    path('change/',views.change_status,name='change')
]

farmup/credits/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from boto3.dynamodb.conditions import Key, Attr
from twilio.rest import Client
import datetime
import uuid
import boto3
import stripe
from django.http.response import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import pandas as pd
# Create your views here.

try:
    import httplib
except:
    import http.client as httplib


def index(request):
    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table('Balances')
    cur = request.session['email']
    redeem_table = dynamodb.Table('pending_redeem')
    redeem_response = redeem_table.scan(
        FilterExpression = Attr('email').eq(cur)
    )

    user = request.session['username']
    response = table.scan(
        FilterExpression = Attr('email').eq(cur)
    )
    if len(response['Items'])>0:
        balance = response['Items'][0]['balance']
    else:
        balance = 100
    if request.method=='POST':
        amount = request.POST['amounts']
        balances = {'bal':balance}
    else:
        balances = {'bal': balance,'amount':redeem_response['Items'][0]['amount']}
    return render(request,'credits/index.html',context=balances)

def pending_redeem(request):
    dynamodb = boto3.resource('dynamodb')
    table_balance = dynamodb.Table('Balances')
    table_pending = dynamodb.Table('pending_redeem')
    cur = request.session['email']
    responses_redeem = table_pending.scan(
        FilterExpression=Attr('email').eq(cur)
    )
    cur = request.session['email']
    if request.method=='POST':
        amount = request.POST.get('redeem_amount',False)
        balance = request.POST.get('balance',False)
        if int(balance) - int(amount) < 0:
            return HttpResponse('<html><p> you have insufficient balanace.  </p><a href="/credits/add_balance/"> You can add balance here. </a></html>')
        # auth_token = '55f9a8db2286ced48a7203fd9b06b512'
        auth_token = '515b1c72219b2b7904e4d56a88dfd69c'
        account_sid = 'ACb702ef99316a96af55ee6415656e9486'
        # auth_token = '0fc2aaf55cca11d1771c8d669c32f25c'

        # account_sid = ''
        dynamodb = boto3.resource('dynamodb')
        table_balance = dynamodb.Table('user')
        cur_user = table_balance.scan(
            FilterExpression = Attr('email').eq(request.session['email'])
        )['Items'][0]
        print(cur_user)
        try:
            phone_number = cur_user['phone_number']
        except:
            return redirect('registration:display_edit_profile')
        client = Client(account_sid, auth_token)
        try:
            print(phone_number)
            client.messages.create(
                to="+91" + str(phone_number),
                from_="+12025190638",
                body="Use {} code for verification.Amount requested to redeem is {}".format(responses_redeem['Items'][0]['code'], amount))
        except:
            return HttpResponse('<html><script>alert("Invalid phone number");window.location="/credits";</script></html>')

    return render(request,'credits/pending_redeem.html')

def verify_sms(request):
    code = request.POST['code']
    dynamodb = boto3.resource('dynamodb')
    table_balance = dynamodb.Table('Balances')
    table_pending = dynamodb.Table('pending_redeem')
    table_order = dynamodb.Table('Order')
    table_user = dynamodb.Table('user')
    cur = request.session['email']
    responses_redeem = table_pending.scan(
        FilterExpression=Attr('email').eq(cur)
    )
    if code!=responses_redeem['Items'][0]['code']:
        return HttpResponse('<html><script>alert("Incorrect code");window.location="/credits/pending_redeem";</script></html>')
    balance = table_balance.scan(
        FilterExpression=Attr('email').eq(cur)
    )
    user = table_user.scan(
        FilterExpression=Attr('email').eq(cur)
    )['Items'][0]['username']
    amount = responses_redeem['Items'][0]['amount']
    balance_user = int(balance['Items'][0]['balance'])
    response = table_balance.update_item(
        Key={
            #'email': user['email'],
            # 'user':user
            'email':request.session['email']
        },
        UpdateExpression="set balance = :r",
        ExpressionAttributeValues={
            ':r': balance_user-int(amount)
        },
        ReturnValues="UPDATED_NEW"
    )
    trans_id = responses_redeem['Items'][0]['transaction_id']
    table_pending.delete_item(
        Key={
            'transaction_id':trans_id
        }
    )
    user_orders = table_order.scan(
        FilterExpression=Attr('email').eq(cur) and Attr('is_purchased').eq(False)
    )['Items']
    order_ids = []
    for i in user_orders:
        order_ids.append(i['order_id'])
    for i in order_ids:
        res = table_order.update_item(
            Key={
                'order_id': i
            },
            UpdateExpression="set is_purchased = :r, delivery_status = :t, ordered_date = :d, ordered_time = :s",
            ExpressionAttributeValues={
                ':r': True,
                ':t': 'Purchased',
                ':d': datetime.date.today().strftime('%B %d,%Y'),
                ':s': datetime.datetime.now().time().strftime('%H:%M:%S')
            },
            ReturnValues="UPDATED_NEW"
        )

    table_tr = dynamodb.Table('transactions')
    table_tr.put_item(
        Item={
            'transaction_id':trans_id,
            'username': request.session['username'],
            'email': request.session['email'],
            'date': datetime.date.today().strftime('%B %d,%Y'),
            'time': datetime.datetime.now().time().strftime('%H:%M:%S'),
            'amount':amount,
            'type':'debit'
        }
    )
    return redirect('tracking:track')


def add_balance(request):
    return render(request,'credits/add_balance.html')

def home(request):
    amount = request.POST['amount']
    dynamodb = boto3.resource('dynamodb')
    # table_balance = dynamodb.Table('Balances')
    table_pending = dynamodb.Table('pending_transactions')
    pending_redeems = table_pending.scan(
        FilterExpression=Attr('email').eq(request.session['email'])
    )['Items']
    trans_ids = [i['transaction_id'] for i in pending_redeems]
    if len(trans_ids)>0:
        for i in trans_ids:
            table_pending.delete_item(
                Key={
                    'transaction_id':i
                }
            )
    trans_id = "CR" + uuid.uuid4().hex[:9].upper()

    table_pending.put_item(
        Item={
            'transaction_id': trans_id,
            'username': request.session['username'],
            'email': request.session['email'],
            'date': datetime.date.today().strftime('%B %d,%Y'),
            'time': datetime.datetime.now().time().strftime('%H:%M:%S'),
            'amount': amount,
            # 'status':'pending'

        }
    )
    return render(request,'credits/home.html')

@csrf_exempt
def stripe_config(request):
    if request.method == 'GET':
        stripe_config = {'publicKey': settings.STRIPE_PUBLISHABLE_KEY}
        return JsonResponse(stripe_config, safe=False)


@csrf_exempt
def create_checkout_session(request):
    if request.method == 'GET':
        domain_url = 'http://127.0.0.1:8000/'
        stripe.api_key = settings.STRIPE_SECRET_KEY
        try:
            dynamodb = boto3.resource('dynamodb')
            table_pending = dynamodb.Table('pending_transactions')
            pending_redeems = table_pending.scan(
                FilterExpression=Attr('email').eq(request.session['email'])
            )['Items']
            trans_id = pending_redeems[0]['transaction_id']
            amt = int(pending_redeems[0]['amount'])*100
            # ?session_id={CHECKOUT_SESSION_ID} means the redirect will have the session ID set as a query param
            checkout_session = stripe.checkout.Session.create(
                # success_url=domain_url + 'success',
                success_url=domain_url + 'credits/success/{CHECKOUT_SESSION_ID}/'+trans_id,
                cancel_url=domain_url + 'credits/cancelled/{CHECKOUT_SESSION_ID}/'+trans_id,
                payment_method_types=['card'],
                # customer_email='santosh.265559@gmail.com',
                billing_address_collection='required',
                shipping_address_collection={
                    'allowed_countries': ['IN'],
                },
                # shipping_address_collection='IN',
                mode='payment',
                line_items=[
                    {
                        'name': 'T-shirt',
                        'quantity': 1,
                        'currency': 'inr',
                        'amount': str(amt),
                    }
                ]
            )
            table_pending.delete_item(
                Key={
                    'transaction_id':trans_id
                }
            )
            return JsonResponse({'sessionId': checkout_session['id']})
        except Exception as e:
            return JsonResponse({'error': str(e)})



def success(request,session_id,trans_id):
    dynamodb = boto3.resource('dynamodb')
    table_balance = dynamodb.Table('Balances')
    balance = table_balance.scan(
        FilterExpression=Attr('email').eq(request.session['email'])
    )
    balance_user = int(balance['Items'][0]['balance'])

    table_transaction= dynamodb.Table('transactions')
    pending_redeems = table_balance.scan(
        FilterExpression=Attr('email').eq(request.session['email'])
    )['Items']
    stripe.api_key = settings.STRIPE_SECRET_KEY
    x = stripe.checkout.Session.retrieve(session_id)
    table_transaction.put_item(
        Item={
            'transaction_id':trans_id,
            'amount': int(x['display_items'][0]['amount']/100),
            'date': datetime.date.today().strftime('%B %d,%Y'),
            'time': datetime.datetime.now().time().strftime('%H:%M:%S'),
            'username': request.session['username'],

farmup/credits/templates/credits/cancelled.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <p>Your payment was cancelled.</p>
    </div>
  </section>
  </body>
</html>

farmup/credits/templates/credits/index.html
{#{% extends 'registration/base.html' %}#}
{% load static from staticfiles %}

{% block headblock %}
    <meta charset="UTF-8">
    <title>Credits</title>
    {#        <link rel="stylesheet" type="text/css" href="{% static 'cart/main.css' %}">#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'cart/font-awesome.min.css' %}">#}
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Da+2:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'homepage/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/timeline.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/home-1-styles.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/fonts/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/fonts/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/slick.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/animation.aos.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/animate.min.css' %}">
    <script src="{% static 'homepage/js/modernizr-custom.js' %}"></script>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Capriola&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Da+2:wght@600&family=Raleway:ital,wght@1,600&display=swap" rel="stylesheet">

    <script>document.getElementsByTagName("html")[0].className += " js";</script>

    <style>

        body{
            {#background-image: url("{% static  'credits/payment.jpeg' %}");#}
            background-color: #b3d7ff; background-color: ;
            position: relative;
            background-repeat: no-repeat;
            background-size: 100%;
        {#font-family: 'Baloo Da 2', cursive;#}
            font-family: 'Capriola', sans-serif;

        }
        .div1{
            background-color: white;
            width:60%;
            height: 470px;
            opacity: 0.9;
            margin-top: 10px;
            border-radius: 30px;

        }
        input,button {
            outline: none;
            border: none;
        }
        input,button:focus {
            border-color: transparent !important;
        }




        .contact100-form-btn {
            display: -webkit-box;
            display: -webkit-flex;
            display: -moz-box;
            display: -ms-flexbox;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 0 20px;
            min-width: 200px;
            height: 50px;
            border-radius: 2px;
            background: #00ad5f;

            font-family:'Capriola', sans-serif;
            font-size: 12px;
            color: #fff;
            line-height: 1.2;
            text-transform: uppercase;
            letter-spacing: 1px;

            -webkit-transition: all 0.4s;
            -o-transition: all 0.4s;
            -moz-transition: all 0.4s;
            transition: all 0.4s;
        }

        .contact100-form-btn:hover {
            background: #333333;
        }

    </style>
{% endblock %}
{% block body %}
    <header>
        <!--NAVIGATION-->
        <div class="main-nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg">
                    <a class="navbar-brand" href="{% url 'landing' %}"><div class="logo-brand"><img src="{% static 'homepage/img/images/logo1.png' %}" alt=""></div></a>
                    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar top-bar"></span>
                        <span class="icon-bar middle-bar"></span>
                        <span class="icon-bar bottom-bar"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link  dropdown-toggle" href="{% url 'landing' %}" data-toggle="dropdown">HOME<span class="caret-drop"></span></a>
                                <ul class="dropdown-menu">
                                    <li class="divider-top"></li>
                                    <li><a class="dropdown-item" href="#">Homepage One</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'shopping_cart:buyingpage' %}">Store</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">SERVICES</a>
                            </li>
                            {% if request.session.username %}
                                <li class="nav-item">
                                    <a href="{% url 'registration:my_profile' %}" class="nav-link" >Welcome {{ request.session.username }}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'registration:logout' %}">LOG OUT</a>
                                </li>
                            {% elif not request.session.username %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'registration:login_display' %}">LOG IN</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'registration:register_display' %}">SIGN UP</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!--NAVIGATION END-->
    </header>

    <center>
        <div class="div1">


            <table>
                {% if bal %}

                    <tr>
                        <td>
                            Available balance:
                        </td>
                        <td>
                            {{ bal }}
                        </td>
                    </tr>
                {% else %}
                    <p class="tabletype">Account not found.</p>
                {% endif %}
            </table>
            <form action="{% url 'pending_redeem' %}" method="post">
                {% csrf_token %}
                <div style="margin-left: 200px">Amount to be redeemed :<input type="number" step="any" required name="redeem_amount" id="redeem_amount" value="{{ amount }}" readonly>
                </div>
                <input type="hidden" name="balance" value="{{ bal }}">
                {#                <div class="container-contact100-form-btn">#}
                <br>
                <input type="submit" class="contact100-form-btn" value="Pay Now">
                <br>
            </form>
            <a href="{% url 'add_balance' %}">  <button class="contact100-form-btn" value="Add Balance"> Add Balance</button><br> </a>

            <a href="{% url 'trans_cancel' %}">  <button class="contact100-form-btn" value="Cancel"> Cancel</button><br><br> </a>


        </div>
    </center>
{% endblock body %}

farmup/credits/templates/credits/pending_redeem.html
{#{% extends 'registration/base.html' %}#}
{% load static %}
{% block headblock %}
            <link rel="stylesheet" href="{% static 'homepage/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/css/timeline.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/css/stylesheet.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/css/home-1-styles.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/css/responsive.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/fonts/font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/fonts/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/css/slick.min.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/css/animation.aos.min.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/css/animate.min.css' %}">
        <script src="{% static 'homepage/js/modernizr-custom.js' %}"></script>

        <script>document.getElementsByTagName("html")[0].className += " js";</script>


    <style>
        .input1 {
	 display: block;
	 {#margin: 2em auto;#}
	 border: none;
	 padding: 0;
	 width: 9ch;
	 background: repeating-linear-gradient(90deg, dimgrey 0, dimgrey 1ch, transparent 0, transparent 1.5ch) 0 100%/ 8.5ch 2px no-repeat;
	 font: 5ch droid sans mono, consolas, monospace;
	 letter-spacing: 0.5ch;
}
 .input1:focus {
	 outline: none;
	 color: #070709;
}
input {
	outline: none;
	border: none;
}
input:focus {
  border-color: transparent !important;
}
input:focus::-webkit-input-placeholder { color:transparent; }
input:focus:-moz-placeholder { color:transparent; }
input:focus::-moz-placeholder { color:transparent; }
input:focus:-ms-input-placeholder { color:transparent; }

textarea:focus::-webkit-input-placeholder { color:transparent; }
textarea:focus:-moz-placeholder { color:transparent; }
textarea:focus::-moz-placeholder { color:transparent; }
textarea:focus:-ms-input-placeholder { color:transparent; }

input::-webkit-input-placeholder { color: #adadad;}
input:-moz-placeholder { color: #adadad;}
input::-moz-placeholder { color: #adadad;}
input:-ms-input-placeholder { color: #adadad;}


    .container-contact100-form-btn {
  width: 100%;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  padding-top: 23px;
}

.contact100-form-btn {
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 0 20px;
  min-width: 200px;
  height: 50px;
  border-radius: 2px;
  background: #00ad5f;

  font-family: Montserrat-Bold;
  font-size: 12px;
  color: #fff;
  line-height: 1.2;
  text-transform: uppercase;
  letter-spacing: 1px;

  -webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
  transition: all 0.4s;
}

.contact100-form-btn:hover {
  background: #333333;
}
        body{
        background-image: url("{% static  'credits/payment.jpeg' %}");
        position: relative;
        background-repeat: no-repeat;
        background-size: 100%;
    }


    </style>
    <script>
         history.pushState(null, null, location.href);
         window.onpopstate = function () {
            history.go(1);
         };
    </script>
    <meta charset="UTF-8">
    <title>Title</title>
{% endblock %}
{% block body %}
            <header>
        <!--NAVIGATION-->
        <div class="main-nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg">
                  <a class="navbar-brand" href="{% url 'landing' %}"><div class="logo-brand"><img src="{% static 'homepage/img/images/logo1.png' %}" alt=""></div></a>
                    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar top-bar"></span>
                        <span class="icon-bar middle-bar"></span>
                        <span class="icon-bar bottom-bar"></span>
                    </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                      <li class="nav-item dropdown">
                        <a class="nav-link  dropdown-toggle" href="{% url 'landing' %}" data-toggle="dropdown">HOME<span class="caret-drop"></span></a>
                        <ul class="dropdown-menu">
                          <li class="divider-top"></li>
                          <li><a class="dropdown-item" href="#">Homepage One</a></li>
                        </ul>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'shopping_cart:buyingpage' %}">Store</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'tracking:track' %}">Track</a>
                      </li>
                        {% if request.session.username %}
                             <li class="nav-item">
                        <a href="{% url 'registration:my_profile' %}" class="nav-link" >Welcome {{ request.session.username }}</a>
                      </li>
                            <li class="nav-item">
                        <a class="nav-link" href="{% url 'registration:logout' %}">LOG OUT</a>
                      </li>
                        {% elif not request.session.username %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'registration:login_display' %}">LOG IN</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'registration:register_display' %}">SIGN UP</a>
                      </li>
                        {% endif %}
                    </ul>
                  </div>
                </nav>
            </div>
        </div>
        <!--NAVIGATION END-->
    </header>
<center>
    Please Enter the verification code sent to your registered mobile number.

    <form action="{% url 'verify_sms' %}" method="post">
        {% csrf_token %}

        <input name="code" id="code" type="text" class="input1" maxlength="6">
        <div class="container-contact100-form-btn">

        <input class="contact100-form-btn" type="submit" value="Submit">
        <a href="/credits/cancel/">
        <input type="button" value="Cancel" class="contact100-form-btn" style="margin-left: 5px">

        </a> </div>
    </form>
   </center>
{% endblock body %}

farmup/credits/templates/credits/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django + Stripe Checkout</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <p>Your payment succeeded.</p>
    </div>
  </section>
  </body>
</html>